name: agenda_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  # iOS style icons
  cupertino_icons: ^1.0.8

  # Calendario
  table_calendar: ^3.0.9

  # HTTP client
  dio: ^5.9.0

  # Routing
  go_router: ^17.0.1

  # Secure storage
  flutter_secure_storage: ^10.0.0

  # Value equality
  equatable: ^2.0.7

  # Localización
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/owner/appointments/
    - assets/data/owner/catalogues/
